# .github/workflows/daily-scrape.yml
name: Daily eBay Scrape

on:
  schedule:
    - cron: "0 2 * * *" # 9PM CST / 10PM EST
  workflow_dispatch: # Manual trigger for testing

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.9"
          cache: true
          version: 2.12.3

      - name: Enable UV and install dependencies
        run: |
          pdm config use_uv true
          pdm install

      - name: Ensure directories exist
        run: |
          mkdir -p public/data/current
          mkdir -p public/data/historical

      - name: Run scraper
        run: |
          .venv/bin/python src/ebay_prusa_scrapper/main.py

      - name: Commit results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/data/current/listings.json
          git add public/data/historical
          git add public/data/metadata.json
          git commit -m "Update scraping results [skip ci]" || exit 0
          git push
